#ifndef FILTER_PARAMETERS_H
#define FILTER_PARAMETERS_H

float VOXEL_GRID_FILTER_SIZE_X = 0.001f;
float VOXEL_GRID_FILTER_SIZE_Y = 0.001f;
float VOXEL_GRID_FILTER_SIZE_Z = 0.001f;

float NORMAL_ESTIMATION_RADIUS = 0.03f;

float OUTLIER_REMOVAL_RADIUS = 0.03f;
float OUTLIER_REMOVAL_NUMBER_OF_NEIGHBOURS = 100;

#endif
